name: haiyuan's blog
author: haiyuan
url: www.xhaiyuan.com
email: 269699181@qq.com
paginate: 5
paginate_path: "/page:num/"
baseurl: /
exclude: ['node_modules', '_site']
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji
defaults:
  -
    values:
      layout: "post"
