name: haiyuan's blog
author: haiyuan
url: https://www.xhaiyuan.com
email: xianhaiyuan@gmail.com
paginate: 8
paginate_path: "/page:num/"
baseurl: /
exclude: ['node_modules', '_site']
gems:
  - jekyll-paginate
markdown: kramdown
defaults:
  -
    values:
      layout: "post"
