name: haiyuan's blog
author: haiyuan
url: www.xhaiyuan.com
email: 269699181@qq.com
uri: https://github.com/xianhaiyuan
paginate: 12
paginate_path: "/page:num/"
baseurl: /xhaiyuan.github.io
exclude: ['node_modules', '_site']
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji
defaults:
  -
    values:
      layout: "post"
